# $Id: GNUmakefile 66241 2012-12-13 18:34:42Z gunter $
# --------------------------------------------------------------
# GNUmakefile for examples module.  Gabriele Cosmo, 06/04/98.
# --------------------------------------------------------------

name := testNTST
G4TARGET := $(name)
G4EXLIB := true

ifndef G4INSTALL
  #G4INSTALL = ../../../../..
  G4INSTALL = /home/Dmitry/geant/geant4.10.02-install/share/Geant4-10.2.1/geant4make

endif

.PHONY: all
all: lib bin

include $(G4INSTALL)/config/binmake.gmk
