# $Id: run2c.mac,v 1.1 2007-10-26 08:34:13 gcosmo Exp $
#
# Macro file for "exampleNTST.cc"
# 
# (can be run in batch, without graphic)
#
/control/verbose 2
/control/saveHistory
/NTST/setDebug 0
#
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
#
# construct the default geometry
# 
#/run/useBgsTran 0
#/run/minEcut 1 MeV
#/run/looperCut 0 MeV
/run/setCut 0.7 mm
/gen/choose evt
#
/run/initialize
/run/beamOn  1000

/NTST/getFieldStats
